/var/spool/slurm/slurmd/job26585/slurm_script: line 14: conda: command not found
/var/spool/slurm/slurmd/job26585/slurm_script: line 17: cd: /u/f_giacomarra/repos/Certified_Generation_4_Planning: No such file or directory
Traceback (most recent call last):
  File "/u/f_giacomarra/repos/Latent_Distilled_Diffusion_4_Cert/Models/score_based/exec_vae.py", line 28, in <module>
    train_data, test_data = get_mnist_dataloader(root='./data/', batch_size=64)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/f_giacomarra/repos/Latent_Distilled_Diffusion_4_Cert/Models/score_based/mnist_data.py", line 14, in get_mnist_dataloader
    torchvision.datasets.MNIST(
  File "/u/f_giacomarra/micromamba/envs/cert/lib/python3.12/site-packages/torchvision/datasets/mnist.py", line 104, in __init__
    self.data, self.targets = self._load_data()
                              ^^^^^^^^^^^^^^^^^
  File "/u/f_giacomarra/micromamba/envs/cert/lib/python3.12/site-packages/torchvision/datasets/mnist.py", line 123, in _load_data
    data = read_image_file(os.path.join(self.raw_folder, image_file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/f_giacomarra/micromamba/envs/cert/lib/python3.12/site-packages/torchvision/datasets/mnist.py", line 553, in read_image_file
    x = read_sn3_pascalvincent_tensor(path, strict=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/f_giacomarra/micromamba/envs/cert/lib/python3.12/site-packages/torchvision/datasets/mnist.py", line 540, in read_sn3_pascalvincent_tensor
    return parsed.view(*s)
           ^^^^^^^^^^^^^^^
RuntimeError: shape '[60000, 28, 28]' is invalid for input of size 262128
